package:
  name: nanomotif
  version: "0.1.0"

source:
  url: https://files.pythonhosted.org/packages/b3/5a/67118f55445066a8b27b92837fe1d4ef8c92936dff4ef2459fe36bc598dd/nanomotif-0.1.0.tar.gz
  sha256: b3fc6657d9cb99ff315eda2a8b3c17654dda9614d25b8d5e157c72e60310ffc4

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - wheel
    - requests
    - numpy ==1.24.4
    - pandas ==2.0.2
    - polars >=0.19
    - seaborn ==0.12.2
    - scipy ==1.10.1
    - networkx ==3.1
    - progressbar2 ==3.53.1
    - Bio >=1.6.2
    - pyarrow >=15.0.2
    - snakemake >=7.32.4


test:
  imports:
    - nanomotif
